repos:
-  repo: https://github.com/PyCQA/pylint
   rev: v2.15.7
   hooks:
   - id: pylint
     additional_dependencies: [numpy, bitarray]
     args: [--disable, "C,R",
            --reports, "n",
            --score, "n", --load-plugins,
            "pylint.extensions.bad_builtin,
             pylint.extensions.check_elif,
             pylint.extensions.code_style,
             pylint.extensions.comparetozero,
             pylint.extensions.emptystring,
             pylint.extensions.overlapping_exceptions,
             pylint.extensions.redefined_variable_type,
             pylint.extensions.typing",
             --py-version, "3.8",
             --msg-template,
             "{path}:{line}: {msg_id} ({symbol}): {msg}",
             --output-format, "text",
             --max-line-length, "79",
             --max-module-lines, "10000",
             --max-args, "9"]
-  repo: https://github.com/PyCQA/flake8
   rev: 3.9.2
   hooks:
   - id: flake8
     additional_dependencies: [# cohesion,
                               # dlint==0.10.2,
                               # flake8-2020==1.7.0,
                               # flake8-adjustable-complexity,
                               # flake8-alfred==v1.0.2,
                               flake8-annotations==2.9.1,
                               flake8-assert-msg==1.1.1,
                               flake8-assertive==2.1.0,
                               # flake8-bandit,
                               flake8-blind-except==0.2.0,
                               # flake8-broken-line,
                               flake8-builtins==2.0.1,
                               flake8-bugbear==22.10.27,
                               # flake8-class-attributes-order,
                               flake8-coding==1.3.2,
                               # flake8-commas,
                               # flake8-cognitive-complexity,
                               flake8-comprehensions==3.10.1,
                               # flake8-comments,
                               # flake8-complex-f-strings,
                               flake8-copyright==0.2.3,
                               # flake8-datetimez,
                               flake8-debugger==4.1.2,
                               flake8-deprecated==2.0.1,
                               flake8-docstrings==1.6.0,
                               # flake8-dunder-all,
                               flake8-encodings==0.4.0,
                               # flake8-eradicate,
                               flake8-executable==2.1.1,
                               # flake8-expression-complexity,
                               # flake8-if-expr,
                               # flake8-import-order,
                               # flake8-intsights,
                               flake8-logging-format==0.6.0,
                               # flake8-loopy,
                               flake8-markdown==0.2.0,
                               # flake8-multiline-containers,
                               flake8-ownership==2.0.1,
                               flake8-pep3101==1.3.0,
                               # flake8-pie==v0.12.0,
                               flake8-polyfill==1.0.2,
                               flake8-print==4.0.0,
                               flake8-printf-formatting==1.1.2,
                               flake8-quotes==3.3.1,
                               flake8-raise==0.0.5,
                               flake8-requirements==1.7.5,
                               # flake8-requests==0.4.0,
                               # flake8-return,
                               flake8-rst==0.8.0,
                               # flake8-rst-docparams,
                               # flake8-rst-docstrings,
                               flake8-secure-coding-standard==1.2.1,
                               flake8-simplify==0.19.3,
                               flake8-sphinx-links==0.2.1,
                               flake8-strftime==0.3.2,
                               # flake8-strict,
                               flake8-string-format==0.3.0,
                               # flake8-spellcheck,
                               flake8-super==0.1.3,
                               flake8-todos==0.1.5,
                               flake8-tuple==0.4.1,
                               # flake8-type-checking==1.0.3,
                               # flake8-typehinting==0.1.0,
                               # flake8-typing-collections==1.0.1,
                               flake8-typing-imports==v1.11.0,
                               flake8-use-fstring==v1.3,
                               # flake8-use-pathlib==0.2.0,
                               # hacking,
                               # pep8-naming,
                               # tryceratops
                               ]
     args: [--ignore,
            "ANN101,ANN102,W503",
            --max-line-length, "79",
            --doctests,
            # flake8-docstrings
            --docstring-convention, "google",
            # flake8-import-order
            # --import-order-style, "pep8",
            # flake8-typing-imports
            --min-python-version, "3.8"
            ]
